version: '3'


services:
  backend-python:
    container_name: backend-python
    build: ./app
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DOMAIN}:${POSTGRES_PORT}/${postgres}
      - SITE_DOMAIN=${SITE_DOMAIN}
      - SITE_PORT=${SITE_PORT}
      - DEBUG=${DEBUG}
    ports:
      - '${SITE_PORT}:8000'
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always

volumes:
  postgres_data:
