"""Add quiz table

Revision ID: 146cf456bf1e
Revises: 
Create Date: 2023-06-12 22:57:17.964422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146cf456bf1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
